#!/usr/bin/env bash
# Uploading a file from client to a remote server

if [ $# -lt 3]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -i $4 -o STRICTHOSTKEYCHECKING=no $1 $3@$2:~/
fi
