#!/usr/bin/env bash
#Installing nginx on a server

sudo apt-get update
sudo apt-get install -y nginx
sudo systemctl status nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx start 
