#!/usr/bin/env bash
#redirecting into some user
apt-get-update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html;
    location /redirect_me {
        return 301 https://twitter.com/TSinishaw;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
