#!/usr/bin/env bash
#Install and configure HaProxy
sudo apt update
sudo apt upgrade
sudo apt install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt update
sudo apt install haproxy
sudo vim /etc/haproxy/haproxy.cfg
echo "frontend haproxy-main
    bind *:80
    option forwardfor
    default_backend apache_webservers

backend apache_webservers
    balance roundrobin
    server web1 100.25.135.61:80 check
    server web2 52.91.154.60:80 check
"| sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy start
